on:
  push:
    tags:
      - v[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: make -j APP="--demo --minify"
      - run: |
          repo=$(echo "$GITHUB_REPOSITORY" | cut --delimiter / --fields 2)
          file=public/manifest.webmanifest
          result=$(jq -c --arg url "/$repo/" '.start_url = $url' "$file")
          echo "$result" > "$file"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
